"use server";

import { db } from "@/lib/db";
import { revalidateTag } from "next/cache";

export async function generateMonthlyPayroll(companyId: string, month: number, year: number) {
  try {
    // 1. Fetch active employees for this company with a gross_salary > 0
    const employees = await db.employee.findMany({
      where: {
        company_id: companyId,
        status: "active",
        is_deleted: false,
        gross_salary: { gt: 0 }
      }
    });

    if (employees.length === 0) {
      return { success: false, error: "No active employees with configured salary found for this company." };
    }

    const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    const monthName = monthNames[month - 1];

    // 2. Determine last day of the payroll month
    const lastDayOfMonth = new Date(year, month, 0);

    // 3. Create transactions for each employee
    const transactionsData = employees.map(emp => ({
      transaction_code: `SAL-${emp.employee_code}-${month}-${year}`,
      company_id: companyId,
      employee_id: emp.id,
      category: "SALARY",
      sub_category: `Salary for ${monthName} ${year}`,
      transaction_date: lastDayOfMonth,
      amount: emp.gross_salary || 0,
      payment_mode: "bank_transfer",
      reference_no: null,
      notes: "Auto-generated by Payroll Module",
      added_by: "system-payroll",
    }));

    // Perform bulk insert
    const result = await db.transaction.createMany({
      data: transactionsData,
      skipDuplicates: true // Skip if transaction_code already exists
    });

    revalidateTag('transactions', 'default');
    return { 
      success: true, 
      count: result.count,
      message: `Successfully generated ${result.count} salary transactions.`
    };
  } catch (error: any) {
    console.error("Failed to generate payroll:", error);
    return { success: false, error: error.message };
  }
}
